# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "SoundtrackDark"
license = "MIT"
licenselink = "https://github.com/spidyxD/GOTProject/tree/master/themes/MovieNight/LICENSE"
description = ""
homepage = "https://github.com/spidyxD/GOTProject/tree/master/themes/MovieNight"
min_version = "0.41.0"
tags = ["library", "soundtracks", "geek","movies", "accessibility", "font awesome"]
features = ["web", "staticman", "simple", "dark", "minimalist", "fast"]
[author]
  name = "Roger Amador"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
